services:
  server:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/rag
    depends_on:
      - qdrant

  watcher:
    build:
      context: .
    container_name: rag-watcher
    command: ["python", "-u", "-m", "watcher.watcher"]
    env_file:
      - .env
    volumes:
      - .:/rag
      - ${WATCH_DIR}:${WATCH_DIR}:ro
    depends_on:
      - server

  qdrant:
    image: qdrant/qdrant
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: