watch_dir: ${WATCH_DIR}
project_name: ${PROJECT_NAME}
chunk_size: 20

watch_extensions:
  - .py
  - .ts
  - .tsx
  - .php
  - .json
  - .sh
  - .yml
  - .md

ignore_dirs:
  - .git
  - node_modules
  - __pycache__
